/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaControladorJugadorHumano.java
 *
 * Created on 19/06/2010, 14:37:10
 */

package Controlador;

import Vista.VentanaObservadoraJugadorHumano;
import Modelo.Turno;
import Modelo.jugadorHumano;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Damian
 */
public class VistaControladorJugadorHumano extends javax.swing.JInternalFrame implements Observer{
private jugadorHumano jh;
VentanaObservadoraJugadorHumano vojh;




    /** Creates new form VistaControladorJugadorHumano */
    public VistaControladorJugadorHumano(int x,int y) {
        initComponents();

        
        this.setLocation(x, y);
        this.jh = new jugadorHumano();
        VentanaObservadoraJugadorHumano v= new VentanaObservadoraJugadorHumano(this.jh);
        this.vojh = v;
        Turno.getTurno().addObserver(this);
        this.setTitle("|| Jugador H.U.M.A.N.O. ||");

        this.add(v);

        this.setVisible(true);
         

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtNuevaLetra = new javax.swing.JTextField();
        lblRepetida = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(261, 416));

        jButton1.setText("cargar...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtNuevaLetra.setMinimumSize(new java.awt.Dimension(40, 20));

        lblRepetida.setText("--------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNuevaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(!this.jh.validoLetraAJugar(txtNuevaLetra.getText().trim())){

            lblRepetida.setText("LETRA REPETIDA CAMPION...");
            txtNuevaLetra.setText("");// TODO add your handling code here:


        }
        else{
               this.setTitle("Jugador Humanoide Nro. 1");
               this.setBackground(Color.BLUE);
               this.jh.setLetraElegida(txtNuevaLetra.getText());
               txtNuevaLetra.setText("");// TODO add your handling code here:
               lblRepetida.setText("");
                this.jh.jugarAhorcado();

            }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblRepetida;
    private javax.swing.JTextField txtNuevaLetra;
    // End of variables declaration//GEN-END:variables

   

   

    /**
     * @return the jh
     */
    public jugadorHumano getJh() {
        return jh;
    }

    /**
     * @param jh the jh to set
     */
    public void setJh(jugadorHumano jh) {
        this.jh = jh;
    }

    public void update(Observable o, Object arg) {
        Turno t = (Turno) arg;
        if(t.cuentaID==1){
            this.setBackground(Color.GREEN);
            this.vojh.setTitle(".:: TE TOCA ::.");
        }
    }



}
