/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaControladorJugadorMaquina.java
 *
 * Created on 13/06/2010, 21:03:49
 */

package Controlador;

import Vista.VentanaObservadoraJugadorMaquina;
import Modelo.JugadorMaquina;
import Modelo.Turno;
import javax.swing.JInternalFrame;

/**
 *
 * @author Damian
 */
public class VistaControladorJugadorMaquina extends javax.swing.JInternalFrame
{
    JugadorMaquina jm;
    Thread j;

    /** Creates new form VistaControladorJugadorMaquina */
    public VistaControladorJugadorMaquina(int x,int y) {
        initComponents();
        Runnable jm1 = new JugadorMaquina();
        //Runnable jm2 = new JugadorMaquina(2,t);
        new Thread(jm1).start();
       // new Thread(jm2).start();

        this.setLocation(x, y);
        VentanaObservadoraJugadorMaquina v= new VentanaObservadoraJugadorMaquina(jm1);
       // VentanaObservadoraJugadorMaquina v2= new VentanaObservadoraJugadorMaquina(jm2);
        this.add(v);
        //this.add(v2);
        this.setTitle("|| Jugador M.A.Q.U.I.N.A. 1 ||");
        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(51, 51, 51)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaControladorJugadorMaquina().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param ventanaObservadoraJugadorMaquina
     */






}
