/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaObservadoraJugadorMaquina.java
 *
 * Created on 13/06/2010, 21:37:54
 */

package Vista;

import Modelo.JugadorMaquina;
import Modelo.JugadorMaquina;
import java.awt.Rectangle;


import java.util.Observable;
import java.util.Observer;



/**
 *
 * @author Damian
 */
public class VentanaObservadoraJugadorMaquina extends javax.swing.JInternalFrame implements Observer{




    /** Creates new form VentanaObservadoraJugadorMaquina
     * @param j
     */
    public VentanaObservadoraJugadorMaquina(Runnable j) {
        initComponents();
        Rectangle r = new Rectangle();
        r.width = 231;
        r.height = 350;
        JugadorMaquina j1 = (JugadorMaquina)j;
        j1.addObserver(this);
        this.setBounds(r);
        this.setLocation(10, 10);
        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLetrasAdivinadas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCantLetras = new javax.swing.JLabel();
        txtGane = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLetraEnJuego = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtLetrasAdivinadas.setFont(new java.awt.Font("Arial", 0, 20));

        jLabel1.setText("Cant. Letras");

        txtCantLetras.setBackground(new java.awt.Color(204, 204, 204));
        txtCantLetras.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtCantLetras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGane.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtGane.setText(":::::::::::::::");

        jLabel2.setFont(new java.awt.Font("Impact", 1, 14));
        jLabel2.setText("Jugador Automatizado");

        jLabel3.setText(":: Letra en Juego ::");

        txtLetraEnJuego.setFont(new java.awt.Font("Tahoma", 2, 24));
        txtLetraEnJuego.setText("@");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(txtLetraEnJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantLetras)))
                        .addContainerGap(213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(223, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtLetrasAdivinadas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtLetraEnJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtGane, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantLetras))
                .addGap(27, 27, 27)
                .addComponent(txtLetrasAdivinadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaObservadoraJugadorMaquina().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel txtCantLetras;
    private javax.swing.JLabel txtGane;
    private javax.swing.JLabel txtLetraEnJuego;
    public javax.swing.JTextField txtLetrasAdivinadas;
    // End of variables declaration//GEN-END:variables
    @Override
public void update(Observable o, Object jugador)
{
        JugadorMaquina j = (JugadorMaquina) jugador;
        String palabra ="";
        if(j.getUltimaLetraJugada()!="")
        txtLetraEnJuego.setText(j.getUltimaLetraJugada());
        txtCantLetras.setText(String.valueOf(j.getLargoPalabra()));

        for(int x=0;x<j.getLargoPalabra();x++)
        {
            if(j.getTablaLetrasAdivinadas().get(x) != null){
            palabra += j.getTablaLetrasAdivinadas().get(x);
            }
            else
            palabra += " - ";
        }
        txtLetrasAdivinadas.setText(palabra);
        if(j.isWinner()==true)
            txtGane.setText("GANEEE!!!");


 }


}
