/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaObservadoraJugadorHumano.java
 *
 * Created on 14/06/2010, 13:54:30
 */

package Vista;

import Modelo.Turno;
import Modelo.jugadorHumano;
import Modelo.jugadorHumano;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Damian
 */
public class VentanaObservadoraJugadorHumano extends javax.swing.JInternalFrame implements Observer{
jugadorHumano jug;
    /** Creates new form VentanaObservadoraJugadorHumano */
    public VentanaObservadoraJugadorHumano(jugadorHumano j) {
        initComponents();
        initComponents();
        this.jug = j;
        Rectangle r = new Rectangle();
        r.width = 231;
        r.height = 330;
        
        j.addObserver(this); //A�ado a esta ventana como observador del jugador humano para que actualice los cambios ---
       
        this.setBounds(r);
        this.setLocation(10, 80);
        this.setVisible(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLetrasAdivinadas = new javax.swing.JTextField();
        txtGane = new javax.swing.JLabel();
        txtCantLetras = new javax.swing.JLabel();
        txtTeToca = new javax.swing.JLabel();
        txtLetraEnJuego = new javax.swing.JLabel();
        lblRepetida = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        setPreferredSize(new java.awt.Dimension(404, 400));

        jLabel1.setText("Cant. Letras");

        txtLetrasAdivinadas.setFont(new java.awt.Font("Arial", 0, 20));

        txtGane.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtGane.setText(":::::::::::::::");

        txtCantLetras.setBackground(new java.awt.Color(204, 204, 204));
        txtCantLetras.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtCantLetras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTeToca.setText(".:::::::::.");

        txtLetraEnJuego.setFont(new java.awt.Font("Tahoma", 0, 24));
        txtLetraEnJuego.setText("...");

        lblRepetida.setText("todo bien...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantLetras)))
                .addContainerGap(179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(txtTeToca)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLetrasAdivinadas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLetraEnJuego)
                            .addComponent(lblRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblRepetida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(txtLetraEnJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGane, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantLetras))
                .addGap(27, 27, 27)
                .addComponent(txtLetrasAdivinadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtTeToca)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblRepetida;
    public javax.swing.JLabel txtCantLetras;
    private javax.swing.JLabel txtGane;
    private javax.swing.JLabel txtLetraEnJuego;
    public javax.swing.JTextField txtLetrasAdivinadas;
    public javax.swing.JLabel txtTeToca;
    // End of variables declaration//GEN-END:variables

public void update(Observable o, Object jugador) {
Toolkit tk = Toolkit.getDefaultToolkit();


   
            jugadorHumano j = (jugadorHumano)jugador;
            
            String palabra ="";
            if(j.getUltimaLetraJugada()!="")
            txtLetraEnJuego.setText(j.getUltimaLetraJugada());
            
            if(j.isMetoca())
            {
                System.out.println("ESTE ES EL IF DE ME TOCA");   
                this.setTitle("Te Toca --->");
                tk.beep();
                this.setBackground(Color.ORANGE);

            }
            else
            {
               this.setTitle(".:::::.");
               this.setBackground(Color.LIGHT_GRAY);
            }

            txtCantLetras.setText(String.valueOf(j.getLargoPalabra()));


        for(int x=0;x<j.getLargoPalabra();x++)
        {

            if(j.getTablaLetrasAdivinadas().get(x) != null){
            palabra += j.getTablaLetrasAdivinadas().get(x);
            }
            else
            palabra += " - ";

        }
            txtLetrasAdivinadas.setText(palabra);
            
        if(j.isWinner()==true)
            txtGane.setText("GANEEE!!!");
        
    }
}
