/*
 * vistaGeneral.java
 *
 * Created on 11 de junio de 2010, 18:40
 */

package Vista;

import Modelo.CargaPalabras;
import javax.swing.UIManager;

/**
 *
 * @author  alumno
 */
public class vistaGeneral extends javax.swing.JInternalFrame {
  
    
    /**
     * Creates new form vistaGeneral
     */
    public vistaGeneral() {
        initComponents();
         //vh = new VistaHumano();
        // vm = new VistaMaquina();
         
         
         this.setSize(850,500);
        // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
         vistaGeneral vista = new vistaGeneral();
         vista.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaGeneral().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
